cash_or_trade/blueprints/listings.py
from flask import Blueprint, render_template, redirect, url_for, request
from cash_or_trade import db_client
from cash_or_trade.extensions import email_client
from cash_or_trade.auth import require_login

listings = Blueprint('listings', __name__, url_prefix='/listings')

@listings.route('/', methods=["GET", "POST"])
def home():
    if request.method == 'POST':
        type_filter = request.form.get('filter')
        all_listings = db_client.all_listings_get(type_filter)
        return render_template('listings/all_listings.html', 
                               all_listings=all_listings,
                               type_filter=type_filter)
    all_listings = db_client.all_listings_get('all')
    return render_template('listings/all_listings.html', 
                           all_listings=all_listings,
                           type_filter='all')

@listings.route('/view/<listing_id>')
def show_listing(listing_id):
    listing = db_client.show_listing_get(listing_id)
    return render_template('/listings/show_listing.html', listing=listing)

@listings.route('/view/<listing_id>/offer', methods=["GET", "POST"])
@require_login
def listing_offer(listing_id):
    if request.method == "POST":
        buyer_username = request.form.get('buyer')
        listing = db_client.show_listing_get(listing_id)
        buyer = db_client.get_user_by_username(buyer_username)
        offer = request.form.get('offer_text')
        email = email_client(buyer, listing, offer)
        return render_template('listings/example_email.html', email=email)
    listing = db_client.show_listing_get(listing_id)
    return render_template('listings/listing_offer.html', listing=listing)

cash_or_trade/blueprints/listings/__init__.py
from flask import Blueprint, render_template, redirect, url_for

listings = Blueprint('listings', __name__, url_prefix='/listings')

templates/listings/all_listings.html
{% extends 'base.html' %}

{% block content %}
    <div class="filter-form">
        <form action="{{ url_for('listings.home')}}" method="POST">
            <p><select id="filter" name="filter">
                <option value="all" {% if type_filter == "all" %}selected{% endif %}>All</option>
                <option value="electronics" {% if type_filter == "electronics" %}selected{% endif %}>Electronics</option>
                <option value="home" {% if type_filter == "home" %}selected{% endif %}>Home</option>
                <option value="kitchen" {% if type_filter == "kitchen" %}selected{% endif %}>Kitchen</option>
                <option value="outdoors" {% if type_filter == "outdoors" %}selected{% endif %}>Outdoors</option>
            </select></p>
            <p><button type="submit" style="margin-top: -10px;"><b>Filter</b></button></p>
        </form>
    </div>   
    <div class="all-listings">
        {% for listing in all_listings %}
            <div class="listing {{listing.type}}">
                <a href="{{ url_for('listings.show_listing', listing_id=listing.id)}}" style="text-decoration: none">
                    <div class="listing-title">
                        <b>{{listing.description.title}}</b>
                    </div>
                    <div class="listing-img">
                        <img id="listing-img-{{listing.id}}" src="">
                    </div>
                    <div class="listing-text">
                        Owner: <b>{{listing.user.username}}</b> - Price: <b>${{listing.price}}</b>
                    </div>
                </a>
            </div>
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    let listingImage = document.getElementById('listing-img-{{listing.id}}')
                    let images = [];
                    if ("{{listing.description.img1}}" !== 'None') {
                        images.push("{{listing.description.img1}}");
                    };
                    if ("{{listing.description.img2}}" !== 'None') {
                        images.push("{{listing.description.img2}}");
                    };
                    if ("{{listing.description.img3}}" !== 'None') {
                        images.push("{{listing.description.img3}}");
                    };
                    if ("{{listing.description.img4}}" !== 'None') {
                        images.push("{{listing.description.img4}}");
                    };
                    if ("{{listing.description.img5}}" !== 'None') {
                        images.push("{{listing.description.img5}}");
                    };
                    updateImage(images, listingImage);
                    })();
            </script>
        {% endfor %}
    </div>

    <script>
        function updateImage(images, listingImage) {
            let currentIndex = 0;
            let previousIndex = 0;
            function setImage() {
                if (images[currentIndex] !== 'None') {
                    listingImage.src = images[currentIndex];
                    previousIndex = currentIndex
                    currentIndex = (currentIndex + 1) % images.length;
                } else {
                    listingImage.src = images[previousIndex]
                    currentIndex = 0
                }
                console.log(images[currentIndex])
            };
            setImage();
            setInterval(setImage, 5000);
        };
    </script>
{% endblock %}

templates/listings/example_email.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center;">Example Email</h2>
    {% for line in email %}
        <p style="text-align: center;">{{line}}</p>
    {% endfor %}
{% endblock %}

templates/listings/listing_offer.html
{% extends 'base.html' %}

{% block content %}
    <div class="offer">
        <div class="offer-listing">
            <div class="offer-listing-text">
                <p><b>{{listing.name}}</b></p>
                <p>$<b>{{listing.price}}</b></p>
                <p>Owner: <b>{{listing.user.username}}</b></p>
            </div>
            <div class="offer-listing-img">
                <img src={{listing.description.img1}}>
            </div>
        </div>
        <div class="offer-form">
            <form action="{{ url_for('listings.listing_offer', listing_id=listing.id) }}" method="POST">
                <h4 style="text-align: center;">Make an Offer: </h4>
                <textarea type="text" name="offer_text" id="offer_text" rows='10' cols='50'></textarea>
                <input type="hidden" name="buyer" value="{{session.username}}">
                <p style="text-align: center;"><button type="submit">Submit Offer</button></p>
            </form>
        </div>
    </div>
{% endblock %}

templates/listings/show_listing.html
{% extends 'base.html' %}

{% block content %}
    <div class="show-listing-title">
        <h2>{{listing.description.title}}</h2>
        <p><b>Owned by User: </b>{{listing.user.username}}</p>
    </div>
    <div class="show-listing">
        <div class="show-listing-text">
            <p><b>Item Name:</b> {{listing.name}}</p>
            <p><b>Price:</b> ${{listing.price}}</p>
            <p style="overflow-wrap: break-word"><b>Description:</b> {{listing.description.descr}}</p>
            <p style="text-align: center; overflow-wrap: break-word">
                {{listing.user.username}} 
                <b>{% if listing.tradeable == True %} IS {% else %} IS NOT {% endif %}</b> 
                willing to Trade this Item.
            </p>
            <p style="text-align: center;">
                <a href="{{ url_for('listings.listing_offer', listing_id=listing.id) }}">
                    <button>Make an Offer</button>
                </a>
            </p>
        </div>
        <div class="show-listing-img"> 
            {% if listing.description.img1 %}
                <a href="{{listing.description.img1}}">
                    <img src="{{listing.description.img1}}">
                </a>
            {% endif %}
            {% if listing.description.img2 %}
                <a href="{{listing.description.img2}}">
                    <img src="{{listing.description.img2}}">
                </a>
            {% endif %}
            {% if listing.description.img3 %}
                <a href="{{listing.description.img3}}">
                    <img src="{{listing.description.img3}}">
                </a>
            {% endif %}
            {% if listing.description.img4 %}
                <a href="{{listing.description.img4}}">
                    <img src="{{listing.description.img4}}">
                </a>
            {% endif %}
            {% if listing.description.img5 %}
            <a href="{{listing.description.img5}}">
                <img src="{{listing.description.img5}}">
            </a>
            {% endif %}
        </div>
    </div>
{% endblock %}