cash_or_trade/blueprints/accounts.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, session
from cash_or_trade import db_client


accounts = Blueprint('accounts', __name__, url_prefix='/accounts')

@accounts.route('/register', methods=["GET", "POST"])
def register():
    if request.method == "POST":
        valid, response = db_client.register_new_user(request.form)
        if valid:
            session['username'] = response
            return redirect(url_for('home'))
        flash(response, category='message')
    return render_template('accounts/register.html')
    
@accounts.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Response will be username if valid or error message
        valid, response = db_client.validate_user_login(request.form)
        if valid:
            session['username'] = response
            return redirect(url_for('home'))
        flash(response, category='message')
    return render_template('accounts/login.html')

@accounts.route('/logout')
def logout():
    session.pop('username')
    return redirect(url_for('home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cash or Trade</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body style="font-family: 'Courier New', Courier, monospace;">
    <h1 style="text-align: center;">Cash or Trade</h1>
    {% if session.username %}
        <p style="text-align: center;">
            <a href="{{ url_for('home') }}">Home</a> -
            <a href="{{ url_for('items.user_items', username=session.username) }}">My Items</a> -
            <a href="{{ url_for('accounts.logout') }}">Logout</a>
        </p>
    {% else %}
        <p style="text-align: center;">
            <a href="{{ url_for('home') }}">Home</a> -
            <a href="{{ url_for('accounts.login') }}">Login</a> - 
            <a href="{{ url_for('accounts.register') }}">Register</a> 
        </p>
    {% endif %}

    {% block content %}
    {% endblock %}

</body>
</html>