cash_or_trade/blueprints/items.py
from flask import Blueprint, render_template, redirect, url_for, session, request
from cash_or_trade import db_client
from cash_or_trade.auth import username_validation

items = Blueprint('items', __name__, url_prefix='/items')

@items.route('/<username>')
@username_validation
def user_items(username):
    user_items = db_client.user_items_get(username)
    return render_template('items/user_items.html', user_items=user_items)

@items.route('/<username>/add', methods=["GET", "POST"])
@username_validation
def add_item(username):
    if request.method == "POST":
        db_client.add_item_post(username, request.form, request.files)
        return redirect(url_for('items.user_items', username=username))
    return render_template('items/add_item.html')

@items.route('/<username>/<item_id>')
@username_validation
def show_item(username, item_id):
    item = db_client.show_user_item_get(username, item_id)
    return render_template('items/show_item.html', item=item)

@items.route('/<username>/<item_id>/edit', methods=["GET", "POST"])
@username_validation
def edit_item(username, item_id):
    item = db_client.show_user_item_get(username, item_id)
    if request.method == "POST":
        db_client.edit_user_item_post(username, item_id, request.form, request.files)
        return redirect(url_for('items.show_item', username=username, item_id=item.id))
    return render_template('items/edit_item.html', item=item)

@items.route('/<username>/<item_id>/delete', methods=["GET", "POST"])
@username_validation
def delete_item(username, item_id):
    if request.method == "POST":
        db_client.delete_item_post(username, item_id)
        return redirect(url_for('items.user_items', username=username))
    item = db_client.show_user_item_get(username, item_id)
    return render_template('items/delete_item.html', item=item)

templates/items/add_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="add-form">
        <form action="{{ url_for('items.add_item', username=session.username) }}" method="POST" enctype="multipart/form-data">
            <div class="add-form-text">
                <p>
                    <label for="name", id="name"><b>Item Name:</b> </label>
                    <input type="text" name="name" id="name" placeholder="Item Name">
                </p>
                <p>
                    <label for="title", id="title"><b>Title for Listing: </b> </label>
                    <input type="text" name="title" id="title" placeholder="Listing Title">
                </p>
                <p>
                    <label for="descr", id="descr"><b>Description: </b> </label>
                    <textarea type="text" name="descr" id="descr" rows='4' cols='28'placeholder="Add a Description"></textarea>
                </p>
                <p>
                    <label for="type", id="type"><b>Type</b> (select): </label>
                    <select id="type", name="type">
                        <option value="electronics">Electronics</option>
                        <option value="home">Home</option>
                        <option value="kitchen">Kitchen</option>
                        <option value="outdoors">Outdoors</option>
                    </select>
                </p>
                <p>
                    <label for="price", id="price"><b>Price:</b> </label>
                    <input type="text" name="price" id="price" placeholder="Item Price">
                </p>
                <p>
                    <label for="tradeable", id="tradeable"><b>Willing to Trade?</b> </label>
                    <input type="checkbox" name="tradeable" id="tradeable" value='True'>
                </p>
                <p>
                    <label for="status", id="status"><b>Status:</b> </label>
                    <select id="status", name="status">
                        <option value="public">Public</option>
                        <option value="private">Private</option>
                    </select>
                </p>
            </div>
            <p>
                <span>
                    <input type="file" id="img1" name="img1">
                </span>
                <span>
                    <input type="file" id="img2" name="img2">
                </span>
                <span>
                    <input type="file" id="img3" name="img3">
                </span>
                <span>
                    <input type="file" id="img4" name="img4">
                </span>
                <span> 
                    <input type="file" id="img5" name="img5">
                </span>
            <p>
                <button type="submit">Submit</button>
            </p>
        </form>
    </div>
{% endblock %}

templates/items/delete_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="delete-item-form">
        <p>Are you sure you want to delete {{item.name}}</p>
        <form action="{{url_for('items.delete_item', username=session.username, item_id=item.id)}}" method="POST">
            <button type="input">Confirm</button>
        </form>
    </div>
{% endblock %}

templates/items/edit_item.html
{% extends 'base.html' %}

{% block content %}
    <form action="{{ url_for('items.edit_item', username=session.username, item_id=item.id) }}" method="POST" enctype="multipart/form-data">
        <div class="edit-form">
            <div class="edit-form-text">
                <p>
                    <label for="name" id="name">Item Name: </label>
                    <input type="text" name="name" id="name" value="{{item.name}}">
                </p>
                <p>
                    <label for="title" id="title">Title for Listing: </label>
                    <input type="text" name="title" id="title" value="{{item.description.title}}">
                </p>
                <p>
                    <label for="descr" id="descr">Item Description: </label>
                    <textarea type="text" name="descr" id="descr" rows='4' cols='28'>{{item.description.descr}}</textarea>
                </p>
                <p>
                    <label for="type" id="type">Item Type (select): </label>
                    <select id="type" name="type" value="{{item.type}}">
                        <option value="electronics"{% if item.type == "electronics" %}selected{% endif %}>Electronics</option>
                        <option value="home" {% if item.type == "home" %}selected{% endif %}>Home</option>
                        <option value="kitchen" {% if item.type == "kitchen" %}selected{% endif %}>Kitchen</option>
                        <option value="outdoors" {% if item.type == "outdoors" %}selected{% endif %}>Outdoors</option>
                    </select>
                </p>
                <p>
                    <label for="price" id="price">Item Price: </label>
                    <input type="text" name="price" id="price" value="{{item.price}}">
                </p>
                <p>
                    <label for="tradeable" id="tradeable">Accept Trades: </label>
                    <input type="checkbox" name="tradeable" id="tradeable" {% if item.tradeable %}checked{% endif %}>
                </p>
                <p>
                    <label for="status" id="status">Item Status: </label>
                    <select id="status" name="status">
                        <option value="public" {% if item.status == "public" %}selected{% endif %}>Public</option>
                        <option value="private" {% if item.status == "private" %}selected{% endif %}>Private</option>
                    </select>
                </p>
                <p style="text-align: center;">
                    <button type="submit">Submit</button>
                </p>
            </div>
            <div class="edit-form-img">
                <p>
                    <img src="{{item.description.img1}}">
                    <input type="file" id="img1" name="img1">
                </p>
                <p>
                    <img src="{{item.description.img2}}">
                    <input type="file" id="img2" name="img2">
                </p>
                <p>
                    <img src="{{item.description.img3}}">
                    <input type="file" id="img3" name="img3">
                </p>
                <p>
                    <img src="{{item.description.img4}}">
                    <input type="file" id="img4" name="img4">
                </p>
                <p>
                    <img src="{{item.description.img5}}">
                    <input type="file" id="img5" name="img5">
                </p>

            </div>
        </div>
    </form>
{% endblock %}

templates/items/show_item.html
{% extends 'base.html' %}

{% block content %}
    <div class="show-user-item">
        <div class="show-user-item-text">
            <p><b>Name:</b> {{item.name}}</p>
            <p><b>Price:</b> ${{item.price}}</p>
            <p><b>Title:</b> {{item.description.title}}</p>
            <p><b>Description</b> {{item.description.descr}}</p>
            <p><b>Type:</b> {{item.type}}</p>
            <p><b>Willing to Trade:</b> {% if item.tradeable==True %} yes {% else %} no {% endif %}</p>
            <p><b>Status:</b> {{item.status}}</p>
            <p style="text-align: center;">
                <a href="{{ url_for('items.edit_item', username=session.username, item_id=item.id)}}" style="text-decoration: none; margin-right: 20px;">
                    <button>Edit</button>
                </a> 
                <a href="{{ url_for('items.delete_item', username=session.username, item_id=item.id) }}">
                    <button>Delete</button>
                </a>
            </p>
        </div>
        <div class="show-user-item-img">
            {% if item.description.img1 %}
                <a href="{{item.description.img1}}">
                    <img src="{{item.description.img1}}">
                </a>
            {% endif %}
            {% if item.description.img2 %}
                <a href="{{item.description.img2}}">
                    <img src="{{item.description.img2}}">
                </a>
            {% endif %}
            {% if item.description.img3 %}
                <a href="{{item.description.img3}}">
                    <img src="{{item.description.img3}}">
                </a>
            {% endif %}
            {% if item.description.img4 %}
                <a href="{{item.description.img4}}">
                    <img src="{{item.description.img4}}">
                </a>
            {% endif %}
            {% if item.description.img5 %}
            <a href="{{item.description.img5}}">
                <img src="{{item.description.img5}}">
            </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/items/user_items.html
{% extends 'base.html' %}

{% block content %}
    <div class="user-items-title">
        <h2>{{session.username}}'s Items</h2>
        <a href="{{ url_for('items.add_item', username=session.username) }}">Add Item</a>
    </div>

<div class="user-items">
    {% for item in user_items %}
        <div class="user-item">
            <a href="{{url_for('items.show_item', username=session.username, item_id=item.id)}}" style="text-decoration: none;">
                <div class="user-items-img">
                    <img src="{{item.description.img1}}">
                </div>
                <div class="user-items-text">
                    <p>{{item.name}}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}